name: zsolt_pro_ai
description: Zsolt Pro AI - magyar nyelvű sportfogadási elemző alkalmazás

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  intl: ^0.20.2

  # AI Szelvény Felismerő
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.16.0

  # Tippmix vonalkód- és QR-kód-beolvasás
  mobile_scanner: 5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
